# Based on Ubuntu 18.04

FROM ubuntu:18.04 AS compile-image
MAINTAINER Gianmauro Cuccuru <gmauro@gmail.com>


RUN apt-get update \
 && apt-get install -q -y --no-install-recommends \
    apt-utils \
    apt-transport-https \
    git \
    build-essential \
    python-pip \
    python-dev \
 && apt-get autoremove \
 && apt-get clean


RUN git clone --recursive -b stable-2.6 https://github.com/ansible/ansible \
 && cd ./ansible \
 && pip install --user --upgrade packaging \
 && pip install --user --upgrade setuptools \
 && pip install --user --upgrade -r ./requirements.txt \
 && make \
 && pip install --user .


FROM ubuntu:18.04 AS build-image
COPY --from=compile-image /root/.local /root/.local

# Make sure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH

RUN apt-get update  \
 && apt-get install -q -y --no-install-recommends \
    python \
    git \
    ca-certificates \
 && apt-get autoremove \
 && apt-get clean
